const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { detectPlatform, pickDownload } = require('../web/lib/platform');

const root = path.join(__dirname, '..');
const web = path.join(root, 'web');

function read(rel) {
  return fs.readFileSync(path.join(web, rel), 'utf8');
}

test('Discord return paths survive encoding so invites redeem on the website', async () => {
  const { pathToFileURL } = require('node:url');
  const { safeAuthNext } = await import(pathToFileURL(path.join(web, 'lib/auth-next.js')).href);
  assert.equal(safeAuthNext('%2Fjoin%2Fbracke%2FabcDEF1234567890abcd'), '/join/bracke/abcDEF1234567890abcd');
  assert.equal(safeAuthNext('/join/bracke/abcDEF1234567890abcd'), '/join/bracke/abcDEF1234567890abcd');
  assert.equal(safeAuthNext('https://evil.example'), '/dashboard');
  assert.equal(safeAuthNext('//evil.example'), '/dashboard');
});

test('the public site is a product gateway, not an Open App splash', () => {
  const page = read('app/page.js');
  const gateway = read('components/public-gateway.js');
  const lockup = read('components/splash-lockup.js');
  const signIn = read('components/discord-sign-in.js');
  const open = read('app/open/page.js');
  const readme = read('README.md');
  assert.match(page, /PublicGateway/);
  assert.match(page, /\/dashboard/);
  assert.doesNotMatch(page, /coachintel:\/\//);
  assert.match(gateway, /SplashLockup/);
  assert.match(lockup, /splash-logo\.png/);
  assert.match(lockup, /splash-wordmark\.png/);
  assert.match(lockup, /splash-slogan\.png/);
  assert.match(signIn, /Sign in with Discord/);
  assert.doesNotMatch(gateway, /coachintel:\/\//);
  assert.match(open, /coachintel:\/\//);
  assert.match(readme, /Root Directory/);
  assert.match(readme, /Coach Intel.*Supabase|not.*ECS/i);
  assert.equal(fs.existsSync(path.join(web, 'public', 'favicon.png')), true);
  assert.equal(fs.existsSync(path.join(web, 'public', 'favicon.ico')), true);
  assert.equal(fs.existsSync(path.join(web, 'app', 'icon.png')), true);
  assert.equal(fs.existsSync(path.join(web, 'app', 'favicon.ico')), false);
  const icon = fs.readFileSync(path.join(web, 'app', 'icon.png'));
  assert.equal(icon.readUInt32BE(16), 64);
  assert.equal(icon.readUInt32BE(20), 64);
  for (const name of ['splash-logo.png', 'splash-wordmark.png', 'splash-slogan.png', 'splash-background.png']) {
    assert.equal(fs.existsSync(path.join(web, 'public', 'assets', name)), true, `${name} must ship with the site`);
  }
});

test('web auth talks only to the Coach Intel Supabase project', () => {
  const config = read('lib/config.js');
  const env = read('.env.example');
  const callback = read('app/auth/callback/route.js');
  const signIn = read('app/sign-in/page.js');
  const gateway = read('components/public-gateway.js');
  assert.match(config, /buzqhwoaoiyeqkvmsghm\.supabase\.co/);
  assert.doesNotMatch(config, /ecs_|AUTH_DATABASE|championshipseries\.supabase/i);
  assert.match(env, /Coach Intel Supabase only/);
  assert.match(env, /\/auth\/callback/);
  assert.match(callback, /exchangeCodeForSession/);
  assert.match(signIn, /InviteGate/);
  assert.doesNotMatch(signIn, /PublicGateway/);
  assert.match(gateway, /DiscordSignIn/);
  const invite = read('lib/invite.js');
  const joinPage = read('app/join/[...parts]/page.js');
  const joinInvite = read('components/join-invite.js');
  const legacyInvite = read('app/invite/[token]/page.js');
  const gate = read('components/invite-gate.js');
  const css = read('app/globals.css');
  const sql = fs.readFileSync(path.join(root, 'scripts', 'supabase', 'schema.sql'), 'utf8');
  assert.match(invite, /invite_preview/);
  assert.match(invite, /redeem_invite/);
  assert.match(invite, /\/join\//);
  assert.match(invite, /You've been selected/);
  assert.match(invite, /inviteeSlug/);
  assert.match(invite, /gamertag/);
  assert.match(read('lib/invite-email.js'), /Coach Intel/);
  assert.match(read('lib/invite-email.js'), /ciLogoSrc/);
  assert.match(read('lib/invite-email.js'), /orgLogoSrc/);
  assert.match(read('lib/invite-email.js'), /teamLogoSrc/);
  assert.match(read('app/join/email-preview/page.js'), /loadInviteFromApp/);
  assert.match(read('app/join/email-preview/page.js'), /previewJoinUrl/);
  assert.match(read('app/join/email-preview/page.js'), /markSrc/);
  assert.doesNotMatch(read('app/join/email-preview/page.js'), /localhost/);
  assert.match(read('app/join/preview/page.js'), /loadInviteFromApp/);
  assert.match(joinPage, /preview/);
  assert.match(gate, /signin-screen/);
  assert.match(gate, /signin-lockup/);
  assert.match(gate, /invite-pass/);
  assert.match(gate, /invite-pass-welcome/);
  assert.match(gate, /Join as/);
  assert.match(gate, /change your profile later in Settings/);
  assert.match(gate, /OrgMark/);
  assert.match(gate, /TeamMark/);
  assert.doesNotMatch(gate, /BrandLockup/);
  assert.doesNotMatch(gate, /SplashLockup/);
  assert.match(gate, /inviteCopy/);
  assert.match(css, /var\(--accent\) 11%/);
  assert.doesNotMatch(css, /intel-wave/);
  assert.doesNotMatch(css, /pitFrostLift/);
  assert.match(sql, /invitee_email/);
  assert.match(sql, /org_name/);
  assert.match(sql, /org_logo/);
  assert.match(sql, /play_role/);
  assert.match(sql, /display_name/);
  assert.match(sql, /update_my_profile/);
  assert.match(sql, /update_my_photo/);
  assert.match(sql, /coalesce\(nullif\(btrim\(display_name\)/);
  assert.match(joinPage, /JoinInvite/);
  assert.match(joinPage, /parts/);
  assert.match(joinInvite, /previewInvite/);
  assert.match(joinInvite, /redeemInvite/);
  assert.match(joinInvite, /inviteeSlug/);
  assert.match(legacyInvite, /redirect\(`\/join\//);
  const oauth = read('components/discord-sign-in.js');
  const middleware = read('middleware.js');
  assert.match(oauth, /redirectTo: `\$\{origin\}\/auth\/callback`/);
  assert.doesNotMatch(oauth, /callback\?next=/);
  assert.match(oauth, /ci-auth-next=\$\{encodeURIComponent\(next\)\}/);
  assert.match(middleware, /pathname !== '\/auth\/callback'/);
  assert.match(middleware, /searchParams\.get\('code'\)/);
});

test('signed-in shell reads teams and members from Supabase', () => {
  const data = read('lib/data.js');
  const dash = read('app/(shell)/dashboard/page.js');
  const hubPage = read('app/(shell)/team-hub/[id]/[[...section]]/page.js');
  const hub = read('components/team-hub.js');
  const roster = read('components/hub-roster.js');
  const calendar = read('app/(shell)/calendar/page.js');
  const nav = read('lib/nav.js');
  const desktopNav = read('components/desktop-nav.js');
  const shell = read('components/desktop-shell.js');
  const topbar = read('components/desktop-topbar.js');
  const settings = read('components/settings-view.js');
  const inviteBtn = read('components/copy-invite.js');
  assert.match(data, /from\('teams'\)/);
  assert.match(data, /from\('members'\)/);
  assert.match(data, /shared_docs/);
  assert.match(dash, /OrgDashboard/);
  assert.match(dash, /loadWorkspace/);
  assert.doesNotMatch(dash, /\{\.\.\.data\}/);
  assert.match(hubPage, /TeamHub/);
  assert.match(hub, /hub-rail/);
  assert.match(hub, /Overview/);
  assert.match(hub, /Roster/);
  assert.match(hub, /Planner/);
  assert.doesNotMatch(roster, /CopyInvite/);
  assert.match(read('lib/hub.js'), /\/team-hub\//);
  assert.match(read('app/(shell)/teams/[id]/[[...section]]/page.js'), /hubPath/);
  assert.match(desktopNav, /item.page === 'teams'/);
  assert.match(desktopNav, /\/team-hub\//);
  assert.doesNotMatch(topbar, /Sign out/);
  assert.match(topbar, /RefreshButton/);
  assert.match(shell, /OrgLiveSync/);
  assert.doesNotMatch(read('components/page-header.js'), /RefreshButton/);
  assert.match(read('components/refresh-button.js'), /router.refresh/);
  assert.match(fs.readFileSync(path.join(root, 'scripts', 'supabase', 'schema.sql'), 'utf8'), /alter publication supabase_realtime add table public.profiles/);
  assert.match(fs.readFileSync(path.join(root, 'scripts', 'supabase', 'schema.sql'), 'utf8'), /is_org_writer/);
  assert.match(fs.readFileSync(path.join(root, 'scripts', 'supabase', 'schema.sql'), 'utf8'), /free_agent/);
  assert.match(fs.readFileSync(path.join(root, 'scripts', 'supabase', 'schema.sql'), 'utf8'), /protect_super_admin_member/);
  assert.match(settings, /Sign out/);
  assert.match(settings, /Your Profile/);
  assert.match(settings, /updateMyProfile/);
  assert.match(settings, /uploadMyPhoto/);
  assert.match(read('lib/docs.js'), /update_my_photo/);
  assert.match(read('components/add-records.js'), /\+ Add Member/);
  assert.match(read('components/add-records.js'), /Entire org/);
  assert.match(settings, /accent-swatch/);
  assert.match(read('components/roster-slot-button.js'), /nextLineupSlot|slot === 'bench'/);
  assert.match(read('app/(shell)/players/page.js'), /RosterSlotButton/);
  assert.match(read('app/(shell)/players/page.js'), /canManageTeam/);
  assert.match(read('app/(shell)/players/page.js'), /player-group-grid/);
  assert.match(read('app/(shell)/players/page.js'), /player-group-mark/);
  assert.match(read('app/(shell)/players/page.js'), /Free Agents/);
  assert.match(read('app/(shell)/players/page.js'), /rosterOnly:\s*true/);
  assert.doesNotMatch(read('app/(shell)/players/page.js'), /title\.slice\(0,\s*2\)/);
  assert.match(read('lib/workspace.js'), /loadRosterCore/);
  assert.match(read('lib/workspace.js'), /rosterOnly/);
  assert.match(read('app/(shell)/layout.js'), /loadRosterCore/);
  assert.match(read('lib/supabase/server.js'), /cache\(/);
  assert.match(fs.readFileSync(path.join(root, 'src/renderer/pages/playersPage.js'), 'utf8'), /Promise\.all\(teams\.map/);
  assert.doesNotMatch(fs.readFileSync(path.join(root, 'src/renderer/pages/playersPage.js'), 'utf8'), /title\.slice\(0,\s*2\)/);
  assert.match(read('lib/auth-next.js'), /safeAuthNext/);
  assert.match(read('app/auth/callback/route.js'), /safeAuthNext/);
  assert.match(read('components/discord-sign-in.js'), /encodeURIComponent\(next\)/);
  assert.match(read('app/(shell)/players/page.js'), /VerifiedMark/);
  assert.match(read('app/(shell)/players/page.js'), /memberDiscordVerified/);
  assert.match(settings, /list-item-row/);
  assert.match(read('components/copy-join-alias.js'), /className="btn sm"/);
  assert.doesNotMatch(read('components/copy-join-alias.js'), /text-link/);
  assert.match(read('components/maps-modes-view.js'), /mapModeArts/);
  assert.match(read('components/maps-modes-view.js'), /map-thumb cover/);
  assert.match(read('components/playbooks-view.js'), /StratBoard/);
  assert.match(read('components/strat-board.js'), /mapLayoutSrc/);
  assert.match(read('components/strat-board.js'), /strat-map-preview/);
  assert.match(read('components/strat-board.js'), /saveStrat/);
  assert.match(read('components/strat-board.js'), /player_positions/);
  assert.match(read('components/settings-view.js'), /isOrgAdmin/);
  assert.doesNotMatch(read('components/settings-view.js'), /Delete All Data/);
  assert.match(fs.readFileSync(path.join(root, 'src/main/main.js'), 'utf8'), /requireOrgAdmin\(\(\) => dataStore\.deleteAllData/);
  assert.match(read('lib/strat-pieces.js'), /spawnPositions/);
  assert.match(read('app/desktop-web.css'), /board-wrap \.strat-map-preview/);
  assert.match(read('components/veto-lab-view.js'), /veto-tile/);
  assert.match(read('components/veto-lab-view.js'), /veto-col/);
  assert.match(read('lib/maps.js'), /colossus\.jpg/);
  assert.match(read('lib/access.js'), /STAFF_ONLY_PAGES/);
  assert.match(read('lib/access.js'), /ORG_TOOL_PAGES/);
  assert.match(inviteBtn, /className="btn sm"/);
  assert.doesNotMatch(inviteBtn, /copy-invite-email/);
  assert.doesNotMatch(read('app/desktop-web.css'), /copy-invite-email/);
  assert.match(read('app/globals.css'), /\.gate \.btn \{/);
  assert.doesNotMatch(read('app/globals.css'), /^\.btn \{/m);
  assert.match(read('app/desktop-web.css'), /#app\.shell \.btn/);
  assert.match(read('app/desktop-web.css'), /min-width:\s*0/);
  assert.match(read('components/hub-overview.js'), /btn primary sm/);
  assert.doesNotMatch(settings, /topbar-signout/);
  assert.match(shell, /ContentMain/);
  assert.match(calendar, /OrgCalendar/);
  assert.match(nav, /label: 'Calendar'/);
  assert.match(nav, /label: 'Intel Feed'/);
  assert.match(nav, /label: 'Team Hub'/);
  assert.match(topbar, /Online · Synced/);
  assert.match(topbar, /verified-mark/);
  assert.match(shell, /id="atmosphere"/);
  assert.match(shell, /id="app"/);
  assert.match(shell, /LookSync/);
  assert.match(shell, /org\?\.accent/);
  assert.match(read('lib/accent.js'), /export function applyAccent/);
  assert.match(read('lib/background.js'), /export function applyBackground/);
  assert.doesNotMatch(read('app/desktop-web.css'), /--accent:\s*#b6f542/);
  assert.match(read('components/settings-shell.js'), /settings-nav/);
  assert.match(read('lib/settings-access.js'), /game-rules/);
  assert.match(read('components/settings-view.js'), /BackgroundCard/);
  assert.doesNotMatch(read('components/team-hub.js'), /<span>Strats & Playbooks<\/span>/);
  assert.match(read('components/org-calendar.js'), /Add Event/);
  assert.match(read('components/org-calendar.js'), /page-header/);
  assert.match(read('app/(shell)/calendar/page.js'), /OrgCalendar/);
  assert.doesNotMatch(read('app/(shell)/calendar/page.js'), /AddEvent/);
  assert.match(read('components/desktop-shell.js'), /id="atmosphere"/);
  assert.doesNotMatch(read('components/desktop-shell.js'), /IntelHud/);
  assert.match(read('app/desktop-web.css'), /background: transparent !important/);
  assert.match(read('components/desktop-nav.js'), /sb-link/);
  assert.match(read('components/desktop-nav.js'), /sb-collapse-label/);
  assert.match(read('app/desktop-ui.css'), /#sidebar\.collapsed \.sb-collapse-label/);
  assert.doesNotMatch(read('app/desktop-ui.css'), /sb-collapse span:not\(\.chev\)/);
  assert.match(settings, /id="web-profile-title"/);
  assert.match(settings, /<select/);
  assert.doesNotMatch(settings, /datalist/);
  assert.match(read('lib/identity.js'), /export function titleChoices/);
  assert.match(fs.readFileSync(path.join(root, 'src/renderer/pages/settings/sections/profile.js'), 'utf8'), /titleChoices/);
  assert.doesNotMatch(fs.readFileSync(path.join(root, 'src/renderer/pages/settings/sections/profile.js'), 'utf8'), /datalist/);
  assert.match(fs.readFileSync(path.join(root, 'src/renderer/styles.css'), 'utf8'), /#sidebar\.collapsed \.sb-collapse-label/);
  assert.match(read('app/(shell)/layout.js'), /desktop-ui\.css/);
  assert.match(read('app/(shell)/layout.js'), /sessionIdentity/);
  assert.match(read('lib/data.js'), /display_name/);
  assert.match(read('lib/data.js'), /listDocs\(supabase, 'strat'\)/);
  assert.match(read('lib/data.js'), /listDocs\(supabase, 'scrim'\)/);
  assert.match(read('components/playbooks-view.js'), /playbooks-rail/);
  assert.match(read('lib/docs.js'), /saveStrat/);
  assert.match(read('lib/marks.js'), /\/api\/assets\//);
  assert.match(read('components/veto-lab-view.js'), /buildVetoSequence/);
  assert.match(read('components/war-room-view.js'), /mapReadiness/);
  assert.match(read('components/scrim-hub-view.js'), /Book Scrim/);
  assert.doesNotMatch(read('app/(shell)/playbooks/page.js'), /SectionPage/);
  assert.doesNotMatch(read('app/(shell)/intel-feed/page.js'), /SectionPage/);
  assert.doesNotMatch(read('app/(shell)/maps-modes/page.js'), /SectionPage/);
  assert.match(read('components/add-match.js'), /Best of 5/);
  assert.match(read('lib/series.js'), /Search & Destroy/);
  assert.match(read('components/needs-review-view.js'), /File stats/);
  assert.match(read('components/scoreboard-read.js'), /Save into stats/);
  assert.match(read('components/database-view.js'), /showsCompetitiveStats/);
  assert.match(read('components/database-view.js'), /VerifiedMark/);
  assert.match(read('lib/marks.js'), /memberIsNaevii/);
  assert.match(read('lib/series.js'), /showsCompetitiveStats/);
  assert.match(read('lib/nav.js'), /label: 'Members'/);
  assert.match(read('app/(shell)/players/page.js'), /title="Members"/);
  assert.match(read('components/settings-view.js'), /export function ProfileCard/);
  assert.match(read('components/roster-transfer.js'), /roster-check/);
  assert.match(read('components/roster-transfer.js'), /TransferMember/);
  assert.match(read('components/roster-transfer.js'), /Transfer selected/);
  assert.doesNotMatch(read('components/roster-transfer.js'), /isProtectedPerson/);
  assert.match(read('app/(shell)/players/page.js'), /TransferMember/);
  assert.match(read('app/desktop-web.css'), /padding: 7px 14px/);
  assert.match(read('app/desktop-web.css'), /#app\.shell \.btn\.refresh-btn/);
  assert.match(read('app/desktop-web.css'), /height: 24px/);
  assert.match(read('app/desktop-ui.css'), /var\(--accent\) 11%/);
});

test('Vercel env example and releases schema are ready to apply', () => {
  const env = read('.env.example');
  const sql = fs.readFileSync(path.join(root, 'scripts', 'supabase', 'releases.sql'), 'utf8');
  assert.match(env, /NEXT_PUBLIC_SUPABASE_URL=/);
  assert.match(env, /NEXT_PUBLIC_SUPABASE_ANON_KEY=/);
  assert.match(env, /Root Directory: web/);
  assert.match(sql, /create table if not exists public\.app_releases/);
  assert.match(sql, /to anon, authenticated/);
  assert.match(sql, /using \(published = true\)/);
});

test('download picker follows the visitor OS and skips empty URLs', () => {
  assert.equal(detectPlatform('Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0)'), 'mac');
  assert.equal(detectPlatform('Mozilla/5.0 (Windows NT 10.0; Win64; x64)'), 'windows');
  assert.equal(detectPlatform('Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)'), 'mobile');

  const release = {
    mac_url: 'https://example.com/mac.zip',
    windows_url: 'https://example.com/win.exe',
  };
  const mac = pickDownload(release, 'mac');
  assert.equal(mac.primary.id, 'mac');
  assert.equal(mac.other.id, 'windows');
  assert.equal(mac.both, null);

  const win = pickDownload(release, 'windows');
  assert.equal(win.primary.id, 'windows');
  assert.equal(win.other.id, 'mac');

  const phone = pickDownload(release, 'mobile');
  assert.equal(phone.primary, null);
  assert.equal(phone.both.length, 2);

  const macOnly = pickDownload({ mac_url: release.mac_url }, 'windows');
  assert.equal(macOnly.primary, null);
  assert.equal(macOnly.other.id, 'mac');
});

test('map covers and layouts resolve to public assets that exist', async () => {
  const { pathToFileURL } = require('node:url');
  const { mapCoverSrc, mapLayoutSrc } = await import(pathToFileURL(path.join(web, 'lib/maps.js')).href);
  assert.equal(mapCoverSrc('Colossus'), '/assets/maps/colossus.jpg');
  assert.equal(mapLayoutSrc('Colossus', 'Hardpoint'), '/assets/maps/colossus-hp.webp');
  assert.equal(mapLayoutSrc('Den', 'Search & Destroy'), '/assets/maps/den-snd.png');
  assert.ok(fs.existsSync(path.join(web, 'public/assets/maps/colossus.jpg')));
  assert.ok(fs.existsSync(path.join(web, 'public/assets/maps/colossus-hp.webp')));
  assert.ok(fs.existsSync(path.join(root, 'data/maps/colossus.jpg')));
  assert.ok(fs.existsSync(path.join(root, 'data/maps/den-hp.png')));
});
